baseURL = "https://mazanivan.github.io/"
languageCode = "en-us"
title = "mazo | cybersec"
theme = "PaperMod"

[params]
  defaultTheme = "dark"
  disableThemeToggle = true
  ShowReadingTime = true
  ShowCodeCopyButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true

[[menu.main]]
  name = "Writeups"
  url = "/writeups/"
  weight = 1

[[menu.main]]
  name = "Projects"
  url = "/projects/"
  weight = 2

[[menu.main]]
  name = "CV"
  url = "/cv/"
  weight = 3

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 4
